baseURL = "https://greenorbit.space"
languageCode = "en-us"
title = "Green Orbit Digital Documentation"
enableRobotsTXT = true

[module]
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false

# Enable minify to reduce file sizes on build
minify = true

[taxonomies]
  tag = "tags"
  category = "categories"

[params]

  [params.ui]
    sidebar_menu_truncate = 100
    language_selector_enable = false
    footer_about_enable = true

  googleAnalytics = "UA-XXXXXXXXX-X"

  copyright = { from_year = 2025, to_year = "", authors = "Green Orbit Digital" }

  privacy_policy = "/privacy-policy/"

  [params.links]

    [[params.links.developer]]
    name = "GitHub"
    url = "https://github.com/greenorbitspace"
    icon = "fab fa-github"

    [[params.links.developer]]
    name = "LinkedIn"
    url = "https://linkedin.com/company/greenorbitdigital"
    icon = "fab fa-linkedin-in"

    [[params.links.developer]]
    name = "Twitter"
    url = "https://twitter.com/greenorbitspace"
    icon = "fab fa-twitter"

  [[params.links.community]]
  name = "UKspace"
  url = "https://ukspace.org"
  icon = "fas fa-globe"

# Main navigation menu
[menu]

  [[menu.main]]
  identifier = "docs"
  name = "Documentation"
  url = "/docs/"
  weight = 1

[languages]

  [languages.en]
  languageName = "English"
  weight = 1
  contentDir = "content/en/"
  title = "Green Orbit Digital Documentation"
  params.time_format_default = "Jan 2, 2006"
  params.time_format_blog = "Jan 2, 2006"

[markup]
  [markup.highlight]
  noClasses = false
  style = "monokai"
  lineNos = true
  guessSyntax = true

[outputs]
  home = ["HTML", "RSS"]

[build]
  writeStats = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"