baseURL = "https://greenorbitspace.github.io/hub/"
title = "Green Orbit User Guide"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "docsy"
enableRobotsTXT = true
minify = true

# Site-wide parameters
[params]
  copyright = "Green Orbit Digital"
  privacy_policy = "/about/privacy/"
  description = "Documentation for Green Orbit's tools and services."
  ui = true
  disableBreadcrumbs = false
  disableSearch = false

  # UI customisation for Docsy
  [params.ui]
    sidebar_menu_truncate = 250
    showBanner = true
    showSidebar = true
    sidebarSearch = true

# Goldmark settings to allow raw HTML rendering
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Output formats
[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

# Clean permalinks for main content sections
[permalinks]
  docs = "/docs/:slug/"
  about = "/about/:slug/"

# Main navigation menu
[menu]
  [[menu.main]]
    identifier = "handbook"
    name = "Handbook"
    url = "/docs/handbook/"
    weight = 10

  [[menu.main]]
    identifier = "glossary"
    name = "Glossary"
    url = "/docs/glossary/"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30

# Google Analytics placeholder (empty, update if needed)
[services]
  [services.googleAnalytics]
    id = ""

# Minimal languages config for single language site
[languages]
  [languages.en]
    title = "Green Orbit User Guide"
    weight = 1

# Suppress warnings about raw HTML in Markdown rendering (set via CLI or config if supported)
# Note: Hugo may not support ignoreLogs in TOML; you can suppress warnings with CLI flag