# Netlify build configuration for Hugo site using Docsy theme

[build]
publish = "public"
command = "npm install && npm run build"

[build.environment]
GO_VERSION = "1.22.3"
NODE_VERSION = "22"
HUGO_VERSION = "0.125.4"  
HUGO_ENABLEGITINFO = "true"
HUGO_THEME = "repo"

[context.production]
command = "npm install && npm run build"

[context.deploy-preview]
command = "npm install && hugo --buildDrafts --buildFuture --minify"

[context.branch-deploy]
command = "npm install && npm run preview"