# Netlify build config for Hugo + Docsy with modules

[build]
  command = "npm install && npm run build"
  publish = "public"

[build.environment]
  GO_VERSION = "1.22.3"
  NODE_VERSION = "22"
  HUGO_VERSION = "0.147.8"            
  HUGO_ENABLEGITINFO = "true"

[context.production]
  command = "npm install && npm run build"

[context.deploy-preview]
  command = "npm install && npm run build"

[context.branch-deploy]
  command = "npm install && npm run preview"