name: Deploy Docsy site to GitHub Pages

on:
  push:
    branches:
      - main  # deploy on pushes to main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.115.0"  # adjust as needed
          extended: true

      # Install npm dependencies if Docsy uses npm for assets
      - name: Install npm dependencies
        run: |
          if [ -f package.json ]; then
            npm ci
          fi

      # Build the Hugo site
      - name: Build site
        run: hugo --minify --gc

      # Add CNAME for custom domain
      - name: Add CNAME
        run: echo "hub.greenorbit.space" > ./public/CNAME

      # Upload build output for Pages
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4